/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersLayoutImport } from './routes/users/_layout'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as UsersLayoutUserIdImport } from './routes/users/_layout.$userId'

// Create Virtual Routes

const UsersImport = createFileRoute('/users')()

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersLayoutRoute = UsersLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => UsersRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const UsersLayoutUserIdRoute = UsersLayoutUserIdImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/users/_layout': {
      id: '/users/_layout'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLayoutImport
      parentRoute: typeof UsersRoute
    }
    '/users/_layout/$userId': {
      id: '/users/_layout/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersLayoutUserIdImport
      parentRoute: typeof UsersLayoutImport
    }
  }
}

// Create and export the route tree

interface UsersLayoutRouteChildren {
  UsersLayoutUserIdRoute: typeof UsersLayoutUserIdRoute
}

const UsersLayoutRouteChildren: UsersLayoutRouteChildren = {
  UsersLayoutUserIdRoute: UsersLayoutUserIdRoute,
}

const UsersLayoutRouteWithChildren = UsersLayoutRoute._addFileChildren(
  UsersLayoutRouteChildren,
)

interface UsersRouteChildren {
  UsersLayoutRoute: typeof UsersLayoutRouteWithChildren
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersLayoutRoute: UsersLayoutRouteWithChildren,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/users': typeof UsersLayoutRouteWithChildren
  '/users/$userId': typeof UsersLayoutUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/users': typeof UsersLayoutRouteWithChildren
  '/users/$userId': typeof UsersLayoutUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/users': typeof UsersRouteWithChildren
  '/users/_layout': typeof UsersLayoutRouteWithChildren
  '/users/_layout/$userId': typeof UsersLayoutUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/users' | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/users' | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/users'
    | '/users/_layout'
    | '/users/_layout/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  UsersRoute: typeof UsersRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  UsersRoute: UsersRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)/login",
        "/(auth)/register",
        "/users"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx"
    },
    "/users": {
      "filePath": "users",
      "children": [
        "/users/_layout"
      ]
    },
    "/users/_layout": {
      "filePath": "users/_layout.tsx",
      "parent": "/users",
      "children": [
        "/users/_layout/$userId"
      ]
    },
    "/users/_layout/$userId": {
      "filePath": "users/_layout.$userId.tsx",
      "parent": "/users/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
